#!/usr/bin/env python3
"""Draw the random sample used to audit the statement-date extractor (v2).

Writes data/date_audit_v2.csv ONCE (it refuses to overwrite it): 40 dated statements drawn at
random (seed 8) from the statements in the date figures, with the public sentence each date was
read from. The columns `verdict` (correct / wrong) and `note` are then filled in by whoever
audits, and the file is never regenerated by run.sh. aggregate.py only reads it.

Verdict rule: "correct" when the sentence shows that the extracted date is the date the
accessibility statement was prepared, reviewed or updated, and it is the latest such date in
the sentence; "wrong" otherwise (a page-edit footer, a clock, a law's date, a date of
something else).
"""
import csv, gzip, json, os, random, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
D = os.path.join(ROOT, "data")
OUT = os.path.join(D, "date_audit_v2.csv")

if os.path.exists(OUT):
    sys.exit(f"{OUT} exists; it holds audit verdicts and is never regenerated")
rows = {r["entity_id"]: r for r in csv.DictReader(open(os.path.join(D, "entities.csv"), encoding="utf-8"))}
recs = {s["entity_id"]: s for s in map(json.loads, gzip.open(os.path.join(D, "records.jsonl.gz"), "rt", encoding="utf-8"))}
cands = sorted(e for e, r in rows.items() if r["stmt_dates_statements"] == "1" and r["stmt_has_date"] == "1"
               and recs[e].get("stmt_date_context"))
random.seed(8)
sample = random.sample(cands, 40)
with open(OUT, "w", newline="", encoding="utf-8") as f:
    w = csv.writer(f)
    w.writerow(["entity_id", "statement_url", "date_method", "extracted_date", "context", "verdict", "note"])
    for e in sample:
        w.writerow([e, rows[e]["acc_url"], rows[e]["date_method"], rows[e]["stmt_latest_date"],
                    recs[e]["stmt_date_context"], "", ""])
print(f"{len(sample)} of {len(cands)} dated statements -> {OUT}")
