#!/usr/bin/env python3
"""Generate the S3 fixture corpus: synthetic images/video/audio carrying
(a) an embedded C2PA manifest with an IPTC digitalSourceType action,
(b) XMP Iptc4xmpExt:DigitalSourceType, (c) the TC260 AIGC XMP field.

Deterministic content; signatures differ per run (timestamps/nonces), so
fixtures are regenerated byte-different but mark-equivalent.

Usage: gen_corpus.py <study_dir>
"""
import json
import random
import shutil
import subprocess
import sys
from pathlib import Path

from PIL import Image, ImageDraw

S = Path(sys.argv[1]).resolve()
FIX = S / "fixtures"
C2PATOOL = S / "tools/c2patool/c2patool"
MANIFEST = S / "scripts/c2pa_manifest.json"
ETCFG = S / "scripts/exiftool-tc260.config"
DST_URI = "http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia"
AIGC_JSON = json.dumps({
    "Label": "1",
    "ContentProducer": "EasyByteLabS3-TEST",
    "ProduceID": "s3-fixture-0001",
    "ReservedCode1": "",
    "ContentPropagator": "",
    "PropagateID": "",
    "ReservedCode2": "",
}, separators=(",", ":"))
REMOTE_URL = "https://example.invalid/s3/manifests/remote-test.c2pa"


def run(cmd, **kw):
    r = subprocess.run([str(c) for c in cmd], capture_output=True, text=True, **kw)
    if r.returncode != 0:
        raise SystemExit(f"FAILED: {' '.join(map(str, cmd))}\n{r.stdout}\n{r.stderr}")
    return r


def base_image() -> Image.Image:
    """800x600 'synthetic' picture: gradient + shapes + seeded noise."""
    w, h = 800, 600
    im = Image.new("RGB", (w, h))
    px = im.load()
    for y in range(h):
        for x in range(w):
            px[x, y] = (int(255 * x / w), int(255 * y / h), 160)
    d = ImageDraw.Draw(im)
    rnd = random.Random(42)
    for _ in range(25):
        x, y, r = rnd.randrange(w), rnd.randrange(h), rnd.randrange(10, 90)
        d.ellipse((x - r, y - r, x + r, y + r),
                  fill=(rnd.randrange(256), rnd.randrange(256), rnd.randrange(256)))
    d.text((20, 20), "EasyByte Lab S3 - synthetic test image", fill=(255, 255, 255))
    return im


def add_xmp(path: Path, dst=True, aigc=True):
    args = ["exiftool", "-config", ETCFG, "-overwrite_original", "-q"]
    if dst:
        args.append(f"-XMP-iptcExt:DigitalSourceType={DST_URI}")
    if aigc:
        args.append(f"-XMP-TC260:AIGC={AIGC_JSON}")
    run(args + [path])


def sign(src: Path, dst: Path, remote: str | None = None):
    cmd = [C2PATOOL, src, "-m", MANIFEST, "-o", dst, "-f"]
    if remote:
        cmd += ["-r", remote]
    run(cmd)


def main():
    img = FIX / "img"
    av = FIX / "av"
    for d in (img, av):
        shutil.rmtree(d, ignore_errors=True)
        d.mkdir(parents=True)
    tmp = S / "work/gen"
    tmp.mkdir(parents=True, exist_ok=True)

    im = base_image()
    for fmt, ext, kw in (("JPEG", "jpg", {"quality": 90}), ("PNG", "png", {}), ("WEBP", "webp", {"quality": 85})):
        none = img / f"{ext}-none.{ext}"
        im.save(none, fmt, **kw)
        # single-mark variants
        x = img / f"{ext}-xmp-dst.{ext}"; shutil.copy(none, x); add_xmp(x, dst=True, aigc=False)
        a = img / f"{ext}-aigc.{ext}"; shutil.copy(none, a); add_xmp(a, dst=False, aigc=True)
        sign(none, img / f"{ext}-c2pa.{ext}")
        # all three marks: XMP first, then C2PA (the claim hashes the XMP)
        t = tmp / f"{ext}-xmp-both.{ext}"; shutil.copy(none, t); add_xmp(t)
        sign(t, img / f"{ext}-all.{ext}")
        # remote-manifest reference (URL under .invalid: never resolvable)
        sign(t, img / f"{ext}-all-remote.{ext}", remote=REMOTE_URL)

    # --- video / audio (ffmpeg synthetic sources) ---
    ff = ["ffmpeg", "-y", "-hide_banner", "-loglevel", "error"]
    mp4 = tmp / "base.mp4"
    run(ff + ["-f", "lavfi", "-i", "testsrc2=size=320x240:rate=25:duration=2",
              "-f", "lavfi", "-i", "sine=frequency=440:duration=2",
              "-c:v", "libx264", "-pix_fmt", "yuv420p", "-crf", "30", "-c:a", "aac", "-b:a", "64k",
              "-shortest", mp4])
    m4a = tmp / "base.m4a"
    run(ff + ["-f", "lavfi", "-i", "sine=frequency=330:duration=3", "-c:a", "aac", "-b:a", "64k", m4a])
    wav = tmp / "base.wav"
    run(ff + ["-f", "lavfi", "-i", "sine=frequency=550:duration=2", "-ac", "1", "-ar", "16000", wav])
    mp3 = tmp / "base.mp3"
    run(ff + ["-f", "lavfi", "-i", "sine=frequency=660:duration=3", "-c:a", "libmp3lame", "-b:a", "64k", mp3])

    shutil.copy(mp4, av / "mp4-none.mp4")
    for src, ext in ((mp4, "mp4"), (m4a, "m4a")):
        t = tmp / f"{ext}-xmp-both.{ext}"; shutil.copy(src, t); add_xmp(t)
        sign(t, av / f"{ext}-all.{ext}")
    for src, ext in ((wav, "wav"), (mp3, "mp3")):
        sign(src, av / f"{ext}-c2pa.{ext}")
    print("corpus ok:", sorted(p.name for p in FIX.rglob("*") if p.is_file() and p.suffix != ".md"))


if __name__ == "__main__":
    main()
