#!/usr/bin/env python3
"""Pivot data/matrix.csv into data/summary.md (one table per input family).
Cell code: C=C2PA (ok / X=broken / -=removed / r=residue), R=remote ref,
D=XMP DigitalSourceType, A=TC260 AIGC (+ survived, - removed, r residue)."""
import csv
import sys
from collections import defaultdict
from pathlib import Path

S = Path(sys.argv[1]).resolve()
rows = list(csv.DictReader(open(S / "data/matrix.csv")))
SYM = {"intact": "ok", "broken": "BROKEN", "removed": "-", "removed_residue": "r",
       "survived": "+", "residue": "r", "error": "err"}
MARK = {"c2pa": "C2PA", "c2pa_remote_ref": "RemoteRef", "xmp_dst": "XMP-DST", "aigc": "AIGC"}

cell = defaultdict(dict)
inputs, marks_of = [], defaultdict(list)
order = []
for r in rows:
    key = (r["transform"], r["output_format"]) if r["transform"] != "identity" else ("identity", "")
    if r["input"] not in inputs:
        inputs.append(r["input"])
    if r["mark"] not in marks_of[r["input"]]:
        marks_of[r["input"]].append(r["mark"])
    cell[(r["input"], r["transform"])][r["mark"]] = SYM.get(r["result"], r["result"])
    if (r["input"], r["transform"], r["output_format"]) not in order:
        order.append((r["input"], r["transform"], r["output_format"]))

lines = ["# S3 survival matrix — summary (generated by scripts/summarize.py)", "",
         "Legend: `ok` C2PA manifest present and hash-valid (only failure: untrusted test cert) · "
         "`BROKEN` manifest present but validation fails · `+` survived · `-` removed · `r` residue (bytes present, not parseable)", ""]
for inp in inputs:
    mk = marks_of[inp]
    lines += [f"## {inp}", "", "| transform | out | " + " | ".join(MARK[m] for m in mk) + " |",
              "|---|---|" + "---|" * len(mk)]
    for (i, t, of) in order:
        if i != inp:
            continue
        lines.append(f"| {t} | {of} | " + " | ".join(cell[(i, t)].get(m, "") for m in mk) + " |")
    lines.append("")

# aggregate by transform across image inputs
agg = defaultdict(lambda: defaultdict(lambda: defaultdict(int)))
for r in rows:
    if r["transform"] == "identity":
        continue
    agg[r["mark"]][r["result"]][r["library"].split(" ")[0]] += 1
lines += ["## Totals by mark and result (all inputs, excluding identity)", "",
          "| mark | result | n | by library |", "|---|---|---|---|"]
for m in MARK:
    for res, libs in sorted(agg[m].items()):
        lines.append(f"| {MARK[m]} | {res} | {sum(libs.values())} | " +
                     ", ".join(f"{k}:{v}" for k, v in sorted(libs.items())) + " |")
(S / "data/summary.md").write_text("\n".join(lines) + "\n")
print("\n".join(lines))

# ---- compact cross-format tables for REPORT.md ----
SY2 = {"intact": "✓", "broken": "✗", "removed": "−", "removed_residue": "r", "survived": "+", "residue": "r"}
def compact(inputs_, marks, title):
    trs = []
    for r in rows:
        if r["input"] in inputs_ and r["transform"] not in trs:
            trs.append(r["transform"])
    idx = {(r["input"], r["transform"], r["mark"]): (SY2.get(r["result"], r["result"]), r["output_format"], r["library"]) for r in rows}
    out = [f"### {title}", "", "| transform | library | out | " + " | ".join(MARK[m] + " (" + "/".join(i.split("-")[0] for i in inputs_) + ")" for m in marks) + " |",
           "|---|---|---|" + "---|" * len(marks)]
    for t in trs:
        lib = next((idx[k][2] for k in idx if k[1] == t), "")
        outs = "/".join(dict.fromkeys(idx[(i, t, marks[0])][1] for i in inputs_ if (i, t, marks[0]) in idx))
        cells = ["/".join(idx.get((i, t, m), ("·",))[0] for i in inputs_) for m in marks]
        out.append(f"| {t} | {lib.split(' (')[0].replace(' via next/image optimizer logic', ' (next/image logic)')} | {outs} | " + " | ".join(cells) + " |")
    return out + [""]

c = ["# Compact tables (generated by scripts/summarize.py)", "",
     "✓ C2PA intact (hash-valid; only failure = untrusted test cert) · ✗ C2PA present but invalid · + survived · − removed · r residue (bytes present, not readable as the standard field) · · not applicable", ""]
c += compact(["jpg-all-remote", "png-all-remote", "webp-all-remote"], ["c2pa", "xmp_dst", "aigc", "c2pa_remote_ref"], "Images (own corpus): JPEG / PNG / WebP inputs")
c += compact(["mp4-all", "m4a-all"], ["c2pa", "xmp_dst", "aigc"], "Video / audio in ISO-BMFF: MP4 / M4A inputs")
c += compact(["wav-c2pa", "mp3-c2pa"], ["c2pa"], "Audio WAV / MP3 inputs (C2PA only)")
c += compact(["pub-CA"], ["c2pa"], "Public sample: c2pa-rs CA.jpg")
(S / "data/summary_compact.md").write_text("\n".join(c) + "\n")
